// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApolloService.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Apollo {
  public static partial class ApolloService
  {
    static readonly string __ServiceName = "Apollo.ApolloService";

    static readonly grpc::Marshaller<global::Apollo.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Apollo.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Apollo.Response> __Marshaller_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Apollo.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::Apollo.Request, global::Apollo.Response> __Method_Call = new grpc::Method<global::Apollo.Request, global::Apollo.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Call",
        __Marshaller_Request,
        __Marshaller_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Apollo.ApolloServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ApolloService</summary>
    public abstract partial class ApolloServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Apollo.Response> Call(global::Apollo.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ApolloService</summary>
    public partial class ApolloServiceClient : grpc::ClientBase<ApolloServiceClient>
    {
      /// <summary>Creates a new client for ApolloService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ApolloServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ApolloService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ApolloServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ApolloServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ApolloServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Apollo.Response Call(global::Apollo.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Call(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Apollo.Response Call(global::Apollo.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Call, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Apollo.Response> CallAsync(global::Apollo.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CallAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Apollo.Response> CallAsync(global::Apollo.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Call, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ApolloServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ApolloServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ApolloServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Call, serviceImpl.Call).Build();
    }

  }
}
#endregion
